@API_HostAddress = https://localhost:8081
@token = 123

# 使用者註冊
POST {{API_HostAddress}}/api/users/register
Content-Type: application/json
{
  "Username": "測試使用者",
  "Email": "test@gmail.com",
  "Password": "aA@12345678",
  "ConfirmPassword": "aA@12345678"
}

###

# 使用者登入
POST {{API_HostAddress}}/api/users/login
Content-Type: application/json
{
  "Email": "test@gmail.com",
  "Password": "aA@12345678"
}

###

# 更新商店名稱
POST {{API_HostAddress}}/api/stores
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Name": "測試商店"
}

###

# 取得指定商店的詳細資訊
GET {{API_HostAddress}}/api/stores/17
Content-Type: application/json
Authorization: Bearer {{token}}
