@API_HostAddress = https://localhost:5001

# 使用者註冊
POST {{API_HostAddress}}/api/users/register
Content-Type: application/json
{
  "Username": "商店擁有者",
  "Email": "StoreOwner@gmail.com",
  "Password": "aA@12345678",
  "ConfirmPassword": "aA@12345678"
}

###

# 註冊第二個使用者
POST {{API_HostAddress}}/api/users/register
Content-Type: application/json
{
  "Username": "商店管理者",
  "Email": "StoreManager@gmail.com",
  "Password": "aA@12345678",
  "ConfirmPassword": "aA@12345678"
}

###

# 使用者登入
# @name login
POST {{API_HostAddress}}/api/users/login
Content-Type: application/json
{
  "Email": "StoreOwner@gmail.com",
  "Password": "aA@12345678"
}

###

@token = {{login.response.body.*}}

###

# 新增商店
POST {{API_HostAddress}}/api/stores
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Name": "使用者測試商店"
}

###

# 授予商店管理員權限
POST {{API_HostAddress}}/api/stores/1/users/2/roles
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Roles": [3]
}

###

# 取得指定商店的詳細資訊
GET {{API_HostAddress}}/api/stores/1
Authorization: Bearer {{token}}

###

# 取得使用者的商店清單

GET {{API_HostAddress}}/api/users/stores
Content-Type: application/json
Authorization: Bearer {{token}}

###