name: Deploy to Cloud Run

on:
    workflow_run:
        workflows: ["CI/CD Pipeline"]
        types:
            - completed

jobs:
    deploy:
        name: Deploy to Cloud Run
        runs-on: ubuntu-latest
        # 只有當CI成功完成，並且標籤名稱以"v"開頭時才執行
        if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_ref, 'refs/tags/v') }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.workflow_run.head_sha }}

            - name: Extract tag name
              id: extract-tag
              run: |
                  TAGNAME=${GITHUB_REF#refs/tags/}
                  echo "TAG=${TAGNAME}" >> $GITHUB_OUTPUT
                  echo "Extracted tag: $TAGNAME"

            - name: Authenticate to Google Cloud
              id: auth
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v1

            - name: Deploy to Cloud Run
              run: |-
                  gcloud run deploy concept-api \
                    --image goodness090807/conceptapi:${{ steps.extract-tag.outputs.TAG || 'latest' }} \
                    --platform managed \
                    --region us-central1 \
                    --allow-unauthenticated \
                    --set-env-vars=TokenService__SecretKey="${{ secrets.TokenService__SecretKey }},TokenService__Issuer=${{ secrets.TokenService__Issuer }},TokenService__Audience=${{ secrets.TokenService__Audience }},ConnectionStrings__DefaultConnection=${{ secrets.ConnectionStrings__DefaultConnection }}" \
                    --project ${{ secrets.GCP_PROJECT_ID }}
